<!--
    This template file is for the Sign In settings.
    File acts as a view file for our Sign In settings.
-->
<?php
    // initialize all values
    $customerLink = $this->showCustomerLink() ?'checked':'';
    $isSPConfigured = $this->isSPConfigured();
    $spDisabled  = $isSPConfigured ? "" : 'disabled title="Disabled. Configure your Service Provider" ';
    $formKey = $this->getBlockHtml('formkey');
    $premiumlink = $this->getExtensionPageUrl('upgrade');
    $isEnabled = $this->isEnabled();
    $enabledebuglog = $this->isDebugLogEnable() ? 'checked':'';
    $disabled = !$isEnabled ? "disabled" : "";

    echo '
    <div class="row">
<div class="col-sm-7 page_margin">
    <div class="page box" id="samlsettings">
    <div class="mosp_table_layout">
        <center><h3>LOGIN/LOGOUT OPTIONS</h3></center>
        <hr>
        <div class="mo_note" >
        <span class="btn-link " >  <span style="color:black;font-weight:normal;text-transform: none;font-size: 16px;" > Available in the <a href="'.$premiumlink.'" class="premium btn-link">premium</a> version</span></span></span>
    </div>
        <form id="signInSettings" method="post" action="">'. $formKey .'
            <input type="hidden" name="option" value="saveSingInSettings" >
            <table>

            <tr>
            <td ><strong style="margin-right:50px">Post-Logout URL:</strong>
           <input type="text"  disabled >
           </td>
    </tr>                   
                <tr>
<td>
                        <h4><b>Show Link on Default Login Page :</b></h4>
                        <div style="margin-left:17px;margin-top:2%;">
                           
                           <input type="checkbox" name="mo_saml_show_customer_link" id="mo_saml_show_customer_link" 
                           '.$customerLink.' value="true">  Show the Login Link on the default customer login page. 
                           <br><br>
                           <input type="checkbox" name="mo_saml_show_admin_link" id="mo_saml_show_admin_link" 
                           disabled> Show the Login Link on the default admin login page.
                      
                        <br><br>  
                        </div>
                        <br> <br>
                       
                        </td>
                </tr>

                </tr>
                <tr><td>
                <lable ><strong>User Auto Create Settings </strong></lable>
                <div style="margin-left:17px;margin-top:2%; width: 100%">	
                
                <input type="checkbox" disabled  name="mo_saml_enable_login_redirect" value="true" 
                      > 
                   Auto Create Admin users while SSO, if they do not exist.
                 <br><br>
                    <input type="checkbox" disabled  name="mo_oauth_enable_all_page_login_redirect" value="true"
                        >
                       Auto Create Customer while SSO, if they do not exist.
               </div>
               
        </td></tr>
        <tr>
        <td>
        <lable ><strong>User Auto Redirect Settings: </strong></lable>
        <div style="margin-left:17px;margin-top:2%; width: 100%">	
        
        <input type="checkbox" disabled  name="mo_saml_enable_login_redirect" value="true" 
              > 
          Check this option to auto redirect users to IDP from login page (if not logged in).
         <br><br>
         <tr><td>
         <h4><b>Use a SSO link:</b></h4>
         <div style="margin-bottom:15px;margin-top:-10px">Use the following link to initiate SSO.</div>
         <div style="font-style: italic;border: 1px solid #c2c2c2;width:550px;height:35px;-webkit-box-shadow: 1px 1px 4px #ebebeb;" >
          <div class="copy-link">
          <input type="text" class="copy-link-input" value="'.$this->getBaseUrl()."mospsaml/actions/sendAuthnRequest".' " readonly>
          <button type="button" class="copy-link-button">
              <span class="material-icons" >
                  <img  src="'.$this->getViewFileUrl('MiniOrange_SP::images/copy.png').'" alt="copy"
                  style="height: 25px;padding-top:4px"
                  >
              </span>
              <span class="copy-text">copied</span>
        </button>
          </div>
          </div>
         </td></tr>
       </div>
        </td>
        </tr>
        
        <tr>
        <td>
<div>
<input type="button" class="btn-round btn-width" name="link_setup" title="You can only make changes if you have configured your SP" 
onclick="document.getElementById(\'signInSettings\').submit();" 
 value="Save">
<br><br>
</div>
        </td>
        </tr>
                
                

            </table>
        </form>
        
        <br><br><br>
        <h3>DEBUG LOGS</h3>
        <hr>
        <form id="enable_debug_log" method="post" action=""> '.$formKey .'
<input type="hidden" name="option" value="enable_debug_log" >
      
        <br>
        <input type="checkbox" name="debug_log_on" '.$enabledebuglog.' value="true" checked>Enable Debug Log

        <input type="button" class="btn-round" name="enable_debug_log"   onclick="document.getElementById(\'enable_debug_log\').submit();"     value="Submit" style="width:110px; margin-left:30px" >
        <br>
</form>
        <form id="clear_download_logs" method="post" action=""> '.$formKey .'
        <input type="hidden" name="option" value="clear_download_logs" >
        <p style="margin-top:20px;margin-left:10px">The error logs will cleared automatically on weekly basis. </p>

        <div style="text-align:left">
        <br>
        <input type="submit" $disabled class="btn-round" name="download_logs"   onclick="document.getElementById(\'download_logs\').submit();"    value="Download Logs" style="width:150px; margin-left:10px">
        <input type="submit" class="btn-round" name="clear_logs"   value="Clear Logs" style="width:150px; margin-left:10px" >
        </div>

        </form>
</div>';



